config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "home#index"  

  get "home/index"

  get 'terms' => 'pages#terms'

  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
		
	validates :title, presence: true
	validates :text, presence: true

	has_many :comments

	def subject
		title
	end

	def last_comment
		comments.last
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only =>[:new, :create]

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article #автоматически редиректит на URL с id которое только что было добавленно "http://127.0.0.1:3000/articles/4"
    else
      render action: 'edit'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new

  end

  def create
    @article = Article.new(article_params)

    if @article.valid?
      @article.save
      redirect_to @article #автоматически редиректит на URL с id которое только что было добавленно "http://127.0.0.1:3000/articles/4"
    else
      render action: 'new'
    end
  end

  def destroy
    @article = Article.find(params[:id])  
    @article.destroy
    redirect_to articles_path
  end

  private 

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, :only =>[:create]

	def create
		@article = Article.find(params[:article_id])
		@article.comments.create(comment_params)

		redirect_to articles_path(@article)
	end

	private

	def comment_params
		params.require(:comment).permit(:author, :body)
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end

  end

  private 

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Редактирование статьи №<%= @article.id %> "<%= @article.title %>"</h1>


<%= form_for :article, url: article_path(@article), method: :put do |f| %>

	<p>
		<%= f.label :title %>
		<br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %>
		<br/>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/index.html.erb
<h1>Список статей:</h1>
<% @articles.each do |article| %>

	<h2><%= article.title %></h2>
	<p><%= article.text %></p>
	<p>
		<%= link_to "Открыть", article_path(article) %> |
		<%= link_to "Изменить", edit_article_path(article) %> |
		<%= button_to "Удалить", article_path(article), method: :delete, data: { turbo_confirm: "Вы действительно хотите удалить статью?" } %>		
	</p>
<hr/>
<% end %>

app/views/articles/new.html.erb
<h1>Новая статья</h1>

<%= form_for :article, url: '/articles' do |f| %>

	<p>
		<%= f.label :title %>
		<br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %>
		<br/>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>

<h2>Комментарии</h2>

<% @article.comments.each do |comment| %>
	<p>
		<i><%= comment.author %> сказал:</i><br/>
		<%= comment.body %>
		<hr>
<% end %>
</p>


<h2>Добавить комментарии:</h2>
<p>
	<%= form_for([@article, @article.comments.build]) do |f| %>
 
		<p>
			<%= f.label :author %>
			<br/>
			<%= f.text_field :author %>
		</p>

		<p>
			<%= f.label :body %>
			<br/>
			<%= f.text_area :body %>
		</p>

		<p>
			<%= f.submit %>
		</p>

	<% end %>
</p>

app/views/contacts/create.html.erb
<h1>Test</h1>

app/views/contacts/new.html.erb
<h1>Контакты</h1>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end	%>
		</ul>
	</p>
	<% end %>
	<p>
		<label>Почта (Email)</label>
		<br/>
		<%= f.text_field :email %>
	</p>

	<p>
		<label>Сообщение</label>
		<br/>
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit 'Отправить сообщение' %>
	</p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>

  <% if user_signed_in? %>

    <%= current_user.username %> <br> <br><%= button_to "Выйти", destroy_user_session_path, method: :delete %>

  <% else %>

    <%= button_to 'Войти', new_user_session_path %> 

  <% end %>

           <p class="notice"><%= notice %></p>                                                                                                                                                                     
           <p class="alert"><%= alert %></p> 

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Тест своих маршрутов About</h1>